# Generated by Django 4.0.2 on 2022-03-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredstudent',
            name='Hostel',
        ),
        migrations.RemoveField(
            model_name='registeredstudent',
            name='SearchKey',
        ),
        migrations.RemoveField(
            model_name='registeredstudent',
            name='Transport',
        ),
        migrations.AlterField(
            model_name='course',
            name='ProgrammeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='RoomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.roomtype', verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.registeredstudent', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='ClassName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.course', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='Programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='SchoolType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schooltype', verbose_name='School Type'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.registeredstudent', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='ClassName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.course', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='Programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.programme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='SchoolType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schooltype', verbose_name='School Type'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicYear', models.CharField(default='', max_length=500)),
                ('ClassName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.course', verbose_name='Class')),
                ('Hostel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.hostelroom', verbose_name='Hostel')),
                ('Programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.programme', verbose_name='Programme')),
                ('RegisteredStudent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.registeredstudent', verbose_name='Student')),
                ('SchoolType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.schooltype', verbose_name='School Type')),
                ('Transport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.assignvehicle', verbose_name='Transport')),
            ],
        ),
    ]
