# Generated by Django 4.0.2 on 2022-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_remove_registeredstudent_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='Description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='AvailableCapacity',
            field=models.IntegerField(default=0, verbose_name='Available Capacity'),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='CurrentCapacity',
            field=models.IntegerField(default=0, verbose_name='Current Capacity'),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='Description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description '),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='Description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description '),
        ),
    ]
