# Generated by Django 4.0.2 on 2022-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_alter_hostel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='LicenceExpiryDate',
            field=models.DateField(verbose_name='Licence Expiry Date'),
        ),
    ]
