# Generated by Django 4.0.2 on 2022-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_alter_driver_licenceexpirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='Status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Not Enrolled', 'Not Enrolled')], default='Not Enrolled', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='AcademicYear',
            field=models.IntegerField(default='Academic Year', max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='AvailableCapacity',
            field=models.IntegerField(default=0, verbose_name='Available Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='CurrentCapacity',
            field=models.IntegerField(default=0, verbose_name='Current Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
    ]
