# Generated by Django 4.0.2 on 2022-03-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_studentenrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='Section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.section', verbose_name='Stream'),
            preserve_default=False,
        ),
    ]
