# Generated by Django 4.0.2 on 2022-03-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_studentenrollment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='Hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.hostelroom', verbose_name='Hostel'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='Transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.assignvehicle', verbose_name='Transport'),
        ),
    ]
