# Generated by Django 4.0.2 on 2022-03-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0007_alter_studentenrollment_hostel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InTime', models.DateTimeField(verbose_name='In Time ')),
                ('OutTime', models.DateTimeField(verbose_name='Out Time')),
                ('TotalHour', models.DateTimeField(verbose_name='Total Hour')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=200, verbose_name='Department ')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesignationName', models.CharField(max_length=200, verbose_name='Designation ')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=200, verbose_name='Department ')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=200, verbose_name='Email')),
                ('EmergencePhoneNumber', models.CharField(max_length=200, verbose_name='Emergence Phone Number')),
                ('DateOfBirth', models.DateField(verbose_name='Date Of Birth')),
                ('JoiningDate', models.DateField(verbose_name='Joining Date')),
                ('Photo', models.ImageField(blank=True, upload_to='images/')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, verbose_name='Marital Status')),
                ('CurrentAddress', models.CharField(max_length=200, verbose_name='Current Address')),
                ('PermanentAddress', models.CharField(max_length=200, verbose_name='Permanent Address')),
                ('Qualification', models.CharField(max_length=200, verbose_name='Qualification')),
                ('WorkExperience', models.CharField(max_length=200, verbose_name='Working Experience')),
                ('Note', models.CharField(max_length=200, verbose_name='Note')),
                ('MedicalInsuranceNumber', models.CharField(max_length=200, verbose_name='Medical Insurance Number')),
                ('DepartmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.department', verbose_name='Department ')),
                ('DesignationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.designation', verbose_name='Designation')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.role', verbose_name='Role ')),
            ],
        ),
        migrations.AlterField(
            model_name='hostel',
            name='Type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixer', 'Mixer')], max_length=200, verbose_name='Hostel Type'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='AcademicYear',
            field=models.IntegerField(default='Academic Year'),
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('InTime', models.DateTimeField(verbose_name='In Time')),
                ('OutTime', models.DateTimeField(verbose_name='Out Time')),
                ('PermissionIn', models.DateTimeField(verbose_name='Permission In')),
                ('PermissionOut', models.DateTimeField(verbose_name='Permission Out')),
                ('TotalHour', models.DateTimeField(blank=True, verbose_name='Total Hour')),
                ('OverTime', models.DateTimeField(verbose_name='Over Time')),
                ('LateSignIn', models.DateTimeField(verbose_name='Late Sign In')),
                ('EarlySignOut', models.DateTimeField(verbose_name='Early Sign Out')),
                ('Remarks', models.CharField(max_length=200)),
                ('DayInfo', models.CharField(max_length=200)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.staff', verbose_name='Staff')),
            ],
        ),
    ]
