# Generated by Django 4.0.2 on 2022-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_product_purchase_sale_supplier_unit_saleitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceconfiguration',
            name='InTime',
            field=models.TimeField(verbose_name='In Time '),
        ),
        migrations.AlterField(
            model_name='attendanceconfiguration',
            name='OutTime',
            field=models.TimeField(verbose_name='Out Time'),
        ),
        migrations.AlterField(
            model_name='attendanceconfiguration',
            name='TotalHour',
            field=models.TimeField(blank=True, verbose_name='Total Hour'),
        ),
    ]
