# Generated by Django 4.0.2 on 2022-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_alter_attendanceconfiguration_intime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceconfiguration',
            name='TotalHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='Total Hour'),
        ),
    ]
