# Generated by Django 4.0.2 on 2022-03-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0011_alter_attendanceconfiguration_totalhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='CurrentAddress',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='EarlySignOut',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Early Sign Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='LateSignIn',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Late Sign In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='OverTime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Over Time'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionIn',
            field=models.DateTimeField(blank=True, verbose_name='Permission In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionOut',
            field=models.DateTimeField(blank=True, verbose_name='Permission Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='TotalHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Total Hour'),
        ),
    ]
