# Generated by Django 4.0.2 on 2022-03-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0012_alter_staff_currentaddress_alter_staff_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='DayInfo',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=200),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='EarlySignOut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Early Sign Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='InTime',
            field=models.TimeField(verbose_name='In Time'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='LateSignIn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Late Sign In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='OutTime',
            field=models.TimeField(verbose_name='Out Time'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionIn',
            field=models.TimeField(blank=True, verbose_name='Permission In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionOut',
            field=models.TimeField(blank=True, verbose_name='Permission Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
