# Generated by Django 4.0.2 on 2022-03-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0013_alter_staffattendance_dayinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='EarlySignOut',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Early Sign Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='LateSignIn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Late Sign In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='OverTime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Over Time'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionIn',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Permission In'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='PermissionOut',
            field=models.TimeField(blank=True, default='00:00:00', verbose_name='Permission Out'),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='TotalHour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Total Hour'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='OpeningBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
