# Generated by Django 4.0.2 on 2022-03-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0014_alter_staffattendance_earlysignout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SystemCategory',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='AgeOrClass',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Age Or Class'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='OpeningBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
