# Generated by Django 4.0.2 on 2022-03-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0015_product_systemcategory_alter_product_ageorclass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='ProductName',
        ),
    ]
