# Generated by Django 4.0.2 on 2022-03-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0017_alter_product_category_alter_purchase_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='BatchNumber',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='AlertDate',
            field=models.DateTimeField(verbose_name='Alert Date'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='ExpiryDate',
            field=models.DateTimeField(verbose_name='Expiry Date'),
        ),
    ]
