# Generated by Django 4.0.2 on 2022-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0018_remove_purchaseitem_batchnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30),
        ),
    ]
