# Generated by Django 4.0.2 on 2022-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0019_alter_product_stock_alter_purchaseitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
    ]
