# Generated by Django 4.0.2 on 2022-03-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0020_alter_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='DiscountAmount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='ExpectedAmount',
        ),
    ]
