# Generated by Django 4.0.2 on 2022-03-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0021_remove_sale_category_remove_sale_discountamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='ActualAmount',
            new_name='Amount',
        ),
    ]
