# Generated by Django 4.0.2 on 2022-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0022_rename_actualamount_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='SaleDate',
            field=models.DateField(verbose_name='Sale Date '),
        ),
    ]
