# Generated by Django 4.0.2 on 2022-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0023_alter_sale_saledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='ExpectedAmount',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
    ]
