# Generated by Django 4.0.2 on 2022-03-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0024_remove_saleitem_expectedamount_saleitem_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('Description', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quarterly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='UnitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='Sale',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='UnitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, verbose_name='Unit Price'),
        ),
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaySlip', models.FileField(upload_to='')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('PendingAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('ReceiptNumber', models.CharField(max_length=200, verbose_name='Receipt Number')),
                ('PaymentDate', models.DateField(verbose_name='Payment Date')),
                ('Status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Uncleared', 'Uncleared')], default='Active', max_length=200)),
                ('PaymentDuration', models.CharField(max_length=200)),
                ('AcademicYear', models.IntegerField(default='Academic Year')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.registeredstudent', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicYear', models.IntegerField(default='Academic Year')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('Description', models.TextField(blank=True, default='', max_length=200)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.course', verbose_name='Class')),
                ('FeeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feetype', verbose_name='Category')),
            ],
        ),
    ]
