# Generated by Django 4.0.2 on 2022-03-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0025_academicyear_feediscount_feetype_monthly_quarterly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='quarterly',
            name='Name',
        ),
        migrations.AddField(
            model_name='monthly',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='April',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='August',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='December',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='Discount',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='February',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='Fee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.fee', verbose_name='Fee'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='FeeCollection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feetype', verbose_name='Fee Collection'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='January',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='July',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='June',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='March',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='May',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='November',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='October',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='monthly',
            name='September',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='Discount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='Fee',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.fee', verbose_name='Fee'),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='FeeCollection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feetype', verbose_name='Fee Collection'),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='QuarterFour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='QuarterOne',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='QuarterThree',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='QuarterTwo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.CreateModel(
            name='FeeCollectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PendingAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('Discount', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount')),
                ('Fee', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.fee', verbose_name='Fee')),
                ('FeeCollection', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feetype', verbose_name='Fee Collection')),
            ],
        ),
    ]
