# Generated by Django 4.0.2 on 2022-03-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0026_remove_monthly_name_remove_quarterly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='AcademicYear',
            field=models.IntegerField(verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='AcademicYear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.academicyear', verbose_name='Academic Year'),
        ),
    ]
