# Generated by Django 4.0.2 on 2022-03-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0027_alter_fee_academicyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='AcademicYear',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.academicyear', verbose_name='Academic Year'),
        ),
    ]
