# Generated by Django 4.0.2 on 2022-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0028_alter_feecollection_academicyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='AcademicYear',
            field=models.IntegerField(default='Academic Year'),
        ),
    ]
