# Generated by Django 4.0.2 on 2022-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0029_alter_feecollection_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecollection',
            name='PaySlip',
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='AcademicYear',
            field=models.IntegerField(default=2022, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='PaymentDuration',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Full', 'Full/Installment')], max_length=200),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='ReceiptNumber',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='Status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Uncleared', 'Uncleared')], default='Uncleared', max_length=200),
        ),
    ]
