# Generated by Django 4.0.2 on 2022-03-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0030_remove_feecollection_payslip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='Status',
            field=models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Uncleared', 'Uncleared')], default='Uncleared', max_length=200),
        ),
        migrations.AlterField(
            model_name='feecollectiondetail',
            name='Discount',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='feecollectiondetail',
            name='FeeCollection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feecollection', verbose_name='Fee Collection'),
        ),
    ]
