# Generated by Django 4.0.2 on 2022-03-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0031_alter_feecollection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollectiondetail',
            name='Discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
    ]
