# Generated by Django 4.0.2 on 2022-04-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0032_alter_feecollectiondetail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly',
            name='PendingAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='quarterly',
            name='PendingAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='monthly',
            name='Fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.fee', verbose_name='Fee'),
        ),
    ]
