# Generated by Django 4.0.2 on 2022-04-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0033_monthly_pendingamount_quarterly_pendingamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='FeeCollection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feecollection', verbose_name='Fee Collection'),
        ),
        migrations.AlterField(
            model_name='quarterly',
            name='FeeCollection',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feecollection', verbose_name='Fee Collection'),
        ),
    ]
