# Generated by Django 4.0.2 on 2022-04-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0034_alter_monthly_feecollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='Discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='quarterly',
            name='Discount',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.feediscount', verbose_name='Discount'),
        ),
    ]
