# Generated by Django 4.0.2 on 2022-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0036_alter_fee_course_alter_monthly_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('MarksFrom', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('MarksTo', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='DivisionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('MarksFrom', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('MarksTo', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('Point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('StartDate', models.DateField(verbose_name='Start Date')),
                ('EndDate', models.DateField(verbose_name='End Date')),
                ('MarksTo', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('Point', models.IntegerField()),
                ('Semester', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GPAGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('MarksFrom', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('MarksTo', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('Point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('GradeType', models.CharField(choices=[('1st Term', '1st Term'), ('2nd Term', '2nd Term')], max_length=200)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('GradeType', models.CharField(max_length=200)),
                ('Semester', models.CharField(max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('Average', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('AverageResult', models.CharField(max_length=200)),
                ('Division', models.IntegerField()),
                ('Point', models.IntegerField()),
                ('ResultMode', models.CharField(choices=[('Avarage', 'Avarage'), ('Division', 'Division'), ('GPA', 'GPA')], max_length=200)),
                ('Status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=200)),
                ('Examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.examination')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.registeredstudent')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.subject')),
            ],
        ),
    ]
