# Generated by Django 4.0.2 on 2022-04-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0037_avarage_divisiongrade_examination_gpagrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='MarksTo',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='Point',
        ),
        migrations.RemoveField(
            model_name='result',
            name='GradeType',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Marks',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Subject',
        ),
        migrations.AddField(
            model_name='result',
            name='AcademicYear',
            field=models.IntegerField(default=2022, verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='resultsubject',
            name='Result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.result'),
        ),
        migrations.AlterField(
            model_name='avarage',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='divisiongrade',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gpagrade',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='Average',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='AverageResult',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='Division',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='Point',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Semester',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
