# Generated by Django 4.0.2 on 2022-04-05 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0039_result_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsubject',
            name='GradeType',
        ),
        migrations.AlterField(
            model_name='result',
            name='AcademicYear',
            field=models.IntegerField(blank=True, default=2022, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='result',
            name='AverageResult',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 5, 23, 14, 29, 403418, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='Division',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Point',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='Semester',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=200),
        ),
        migrations.AlterField(
            model_name='resultsubject',
            name='Subject',
            field=models.CharField(max_length=200),
        ),
    ]
