# Generated by Django 4.0.2 on 2022-07-11 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0045_remove_programme_schoolid_alter_result_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description1', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images')),
                ('Title', models.CharField(max_length=50)),
                ('Description1', models.TextField(max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images/Events/Gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images')),
                ('Title', models.CharField(max_length=50)),
                ('Description1', models.TextField(max_length=200)),
                ('Description2', models.TextField(blank=True, max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='Date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 11, 18, 40, 45, 820992, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='images/Events/')),
                ('Title', models.CharField(max_length=50)),
                ('Description1', models.TextField(max_length=200)),
                ('Description2', models.TextField(blank=True, max_length=200)),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.category', verbose_name='Category')),
                ('Gallery', models.ManyToManyField(to='SchoolApp.Gallery')),
            ],
        ),
    ]
